[package]
name = "bevy_horizon"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_app = { path = "../../vendor/bevy/crates/bevy_app" }
bevy_ecs = { path = "../../vendor/bevy/crates/bevy_ecs" }
bevy_tasks = { path = "../../vendor/bevy/crates/bevy_tasks" }
bevy_window = { path = "../../vendor/bevy/crates/bevy_window" }
